### ISSUE TITLE
Add a reactor right click menu and put there a button to swap waldo colors

### ISSUE THREAD

**Issue by 12345ieee** [csaboka/spacechempatch#32]
The game has no right click menu when not hovering over a symbol, so we can put there our own to do global actions on symbol groups, like:

- [x] color swapping
- [x] mirror vertically
- [x] reset reactor
- [ ] save to toolbox for researches (how to load it back remains to be seen)

That menu would also be a good place to add other level-related commands like the tourney logic of #24 .

**Comment by csaboka** [comment]
All but one of the subtasks have been implemented in v1013 of the main game. Created [#2 in Community Edition](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition/issues/2) to track the remaining subtask. I'm closing this issue now.
