### ISSUE TITLE
Record 1-reactor productions as if they were researches

### ISSUE THREAD

**Issue by 12345ieee** [csaboka/spacechempatch#33]
For 1 reactor productions, add a button below the video recording one, to record it as if it was a research.

Optionally try to show the pipeline for the first couple seconds.

Originally reported by Andy.

**Comment by andy75381** [comment]
The other video recording improvements I was thinking of are:

- Allow recording different number of outputs (extra buttons?). This has two use cases - large output research levels that need more outputs to see the full cycle and very slow min symbols/reactors solutions that take a long time to show the same cycle repeating 4 times.

- Allow recording at higher speed for very slow min symbols/reactors solutions. Variable speed using high speed when nothing much is happening and low speed around inputs, outputs, bonding, etc. would be a better but harder alternative.

**Comment by csaboka** [comment]
Migrated Andy's extra ideas to [#3 of the Community Edition](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition/issues/3). The base idea is implemented in CE already, although in a slightly different way. (You need to enable the feature, then solve the level with the desired reactor open to get a recording of that reactor.)

I'm closing this issue, please use the CE version for further comments.
