### ISSUE TITLE
random inputs reset to even amounts when edited

### ISSUE THREAD

**Issue by gggol** [csaboka/spacechempatch#36]
Random inputs need not have even odds.  It does not have to be 50-50 for two inputs, nor 33-33-33 for three inputs.  The problem is, for puzzles that have random inputs with uneven odds, the slider resets to even odds when the players selects "edit input" alpha, beta, or R (for production puzzles).  The sliders should not change the odds, should not reset.  The odds should change only when the player moves the sliders.

**Comment by csaboka** [comment]
This issue is fixed in the [Community Edition](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition). Please open a new issue in the issue tracker over there if it doesn't work as expected.
