### ISSUE TITLE
Remove "Return to assignment selection screen" question

### ISSUE THREAD

**Issue by gggol** [csaboka/spacechempatch#37]
When the player clicks "Exit" in a puzzle while on any cycle greater than 0, or when the player hits the Esc key, the game throws up a question:  "Return to assignment selection screen?  Your solution will be automatically saved."  I have always found that statement and question a little confusing as well as useless.  It suggests there could be situations where your solution is not saved, and as far as I've ever seen, solutions are always saved regardless.  Better just to remove that question.

**Comment by csaboka** [comment]
This is implemented as an option in the [Community Edition](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition). Please open a new issue in the issue tracker over there if it doesn't work as expected.
