### ISSUE TITLE
waldo direction indicator

### ISSUE THREAD

**Issue by gggol** [csaboka/spacechempatch#38]
Would like some indication of which way a waldo is moving when the simulation is paused.  All the time wouldn't hurt either.  As it is, when paused, not obvious which way the waldo is going on a line it travels in both directions.

For instance, add a tail to the trailing side of the waldo.  Not really room for an arrow on the leading edge, but maybe could do a color brightening, like a heat shield on a spacecraft reentering the atmosphere.  Or, make the line it just followed wider and/or brighter.

**Comment by csaboka** [comment]
This is implemented as an option in the [Community Edition](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition). Please open a new issue in the issue tracker over there if it doesn't work as expected.
