### ISSUE TITLE
Generate reactor screen shots when recording solutions to production levels

### ISSUE THREAD

**Issue by andy75381** [csaboka/spacechempatch#39]
Reactor details are too small in video so we tend to link to images of reactors from videos. It would be convenient to generate these images when a video is generated. Alternatively the video generation could be improved to better show the reactor details.

**Comment by 12345ieee** [comment]
Related to #33 .

**Comment by csaboka** [comment]
This issue has been migrated to [#4 of the Community Edition](https://github.com/spacechem-community-developers/SpaceChem-Community-Edition/issues/4). I'm closing it here, but feel free to comment on the migrated version.
